#!/usr/bin/env bash
# Requirements:
#install nginx on your webserver, configure nginx to run on port 80.

# Install Nginx
apt-get update
apt-get install -y nginx

# Start Nginx service
service nginx start

# Configure Nginx to listen on port 80
sed -i 's/^.*listen.*$/\tlisten 80 default_server;/g' /etc/nginx/sites-available/default

# Reload Nginx configuration
service nginx reload

# Create index.html with "Hello World!"
echo "Hello World!" > /var/www/html/index.html
